number1=input("Enter 1st  number to be swapped:")
number2=input("Enter 2nd  number to be swapped:")
number3=input("Enter 3rd  number to be swapped:")
number=number2
number2=number3
number3=number1
print("After swapping value of first number=",number)
print("After swapping value of second=",number2)
print("After swapping value of third=",number3)
